# Generated by Django 2.2 on 2020-11-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeaFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfd_yyyy', models.CharField(blank=True, max_length=4)),
                ('sfd_mm', models.CharField(blank=True, max_length=2)),
                ('sfd_dd', models.CharField(blank=True, max_length=2)),
                ('sfd_species', models.CharField(blank=True, max_length=50)),
                ('sfd_orign', models.CharField(blank=True, max_length=50)),
                ('sfd_standard', models.CharField(blank=True, max_length=30)),
                ('packing_uint', models.CharField(blank=True, max_length=30)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('highest', models.IntegerField(blank=True, null=True)),
                ('lowest', models.IntegerField(blank=True, null=True)),
                ('average', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seafood',
            },
        ),
    ]
